# 009 - The FILTER keyword - part 2
# ---------------------------------
# 
# We can also filter values using the usual comparison operators:
# 

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT ?mountain ?elevation WHERE
{
	?mountain rdf:type 		dbo:Mountain ;
			  dbo:elevation	?elevation .
			  
	FILTER ( ((?elevation >= 7000) && (?elevation < 8000)) ||
			 (?mountain = dbr:Mount_Everest)  )
}
LIMIT 100

#
# For instance, the above query lists the mountains with an elevation
# between 7000 and 8000 meters, or the mountain whose URI is 
# http://dbpedia.org/resource/Mount_Everest.
# 
# Notice these two logical operators:
# 
# && 	Logical AND
# || 	Logical OR
# 
# A complete list of SPARQL operators is defined here:
# 
# http://www.w3.org/TR/2013/REC-sparql11-query-20130321/#OperatorMapping
# 

