# 
# 011 - Filtering for the presence or absence of a pattern
# --------------------------------------------------------
# 
# You can filter the results of a query to test whether a pattern can be
# found or not in the results data.
# 
# This is done with the FILTER EXISTS and FILTER NOT EXISTS keywords.
# 
# For example, we can add a FILTER NOT EXISTS to query 005 to filter out 
# all found patterns that have a dbo:capital predicate. This will
# eliminate all results that are countries.
# 

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT ?subject WHERE 
{
	dbr:Switzerland foaf:name ?subjectName .
	?subject foaf:name ?subjectName .
	
	FILTER NOT EXISTS {?subject dbo:capital ?capital}
}

