# 006 - The rdf:type predicate and the a keyword
# ---------------------------------------------- 
# 
# Speaking of predicates, one of the most widely used predicates is 
# 
# <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
# 
# which is normally written as rdf:type after the usual prefix attached to
# the rdf syntax vocabulary.
# 
# This predicate is used in a triple to indicate that an object belongs to 
# a certain type.
# 
# Example: 
# <http://dbpedia.org/resource/Tim_Berners-Lee> 
# rdf:type 
# <http://dbpedia.org/ontology/Person>
# 
# Of course, the same object can (and normally will) appear in many rdf:type triples.
# For instance, in the dbpedia rdf database, Tim Berners-Lee also appears in the 
# following triple:
# 
# <http://dbpedia.org/resource/Tim_Berners-Lee> 
# rdf:type 
# yago:FellowsOfTheRoyalSociety
# 
# indicating that he is a member of the royal society. 
# 
# Well, back to rdf:type -- that is so commonly used as a predicate that it can
# be replaced with a specific SPARQL keyword: a (case sensitive).
# 
# For instance, we can rewrite the query in script 004 in a more compact (and 
# nicer) way by using the a keyword instead of the rdf:type predicate.
# 

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> # Friend of a Friend (FOAF) vocabulary
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbprop: <http://dbpedia.org/property/>

SELECT ?object WHERE
{
	?object a foaf:Person ;
			a dbo:SoccerPlayer ;
			dbprop:position dbr:Midfielder ;
			dbprop:clubs dbr:A.S._Roma .
}
LIMIT 10