PREFIX dbo: <http://dbpedia.org/ontology/> # 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> # Friend of a Friend (FOAF) vocabulary
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#> # The RDF Schema vocabulary (RDFS)
PREFIX skos: <http://www.w3.org/2004/02/skos/core> # 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>        
PREFIX type: <http://dbpedia.org/class/yago/>
PREFIX prop: <http://dbpedia.org/property/>

SELECT DISTINCT ?country_name ?wikiPage ?population
WHERE {
    ?country a type:LandlockedCountries ;
             rdfs:label ?country_name ;
             prop:populationEstimate ?population ;
             foaf:isPrimaryTopicOf ?wikiPage
    # FILTER (?population > 15000000) .
    FILTER (lang(?country_name) = "en") .
}ORDER BY DESC(?population)