# 001. Namespaces
# -----------------
# 
# We have seen a simple query example:
# 
# SELECT ?birthDate WHERE
# {
# 	<http://dbpedia.org/resource/Tim_Berners-Lee> <http://dbpedia.org/ontology/birthDate> ?birthDate 
# }
# 
# As you may have noticed, it can get cumbersome to type complete URI identifiers
# like this: <http://dbpedia.org/resource/Tim_Berners-Lee>.
# 
# That's why SPARQL provides the possibility to define namespaces in your 
# query. You do that with the PREFIX keyword:
# 

PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>

# You define prefixes at the top of your query, before other statements.
# 
# Now, we can rewrite the same query of the previous tutorial script, in a 
# bit more friendly and concise way:
# 

SELECT ?birthDate WHERE
{
	dbr:Tim_Berners-Lee dbo:birthDate ?birthDate 
}

#
# If you try running the query, you will see that it will yield the same
# result as the previous version.
#
# Good! Let's move on.
#

