# 006 - Getting a list of landlocked countries
# --------------------------------------------
# 
# Here is possibly the simplest way to obtain a list of landlocked
# countries from dbpedia:
# 

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX yago: <http://dbpedia.org/class/yago/>

SELECT ?country WHERE 
{
    ?country rdf:type dbo:Country;
             rdf:type yago:WikicatLandlockedCountries
   
}


#
# This query returns 43 results.
# Now you might say, wait a minute, why do I need to specify the second
# triple pattern? After all, if an object is a landlocked country it must
# also be a country.
# 
# Good point. However, if you leave the second triple pattern out, you 
# will also obtain the <http://dbpedia.org/Landlocked_Country> result
# (the wikipedia resource that gives the definition of a landllocked country).
# 
# So the second triple pattern is there to make sure that we just get back a list
# of countries, and not entities that -- for a reason or another -- happen to have
# the LandlockedCountries type. 
# 
