# 
# 010 - The FILTER Keyword - Specifying data types
# 
# If necessary, you can specify data types by using the ^^ sequence. 
# This is a typical case when this is done:
# 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?event ?date ?abstract ?wikiPage WHERE
{
	?event 	rdf:type dbo:Event ;
			dbo:date ?date;
			rdfs:label ?eventName;
			foaf:isPrimaryTopicOf ?wikiPage.

	FILTER ( (?date >= "1861-01-01"^^xsd:date) &&
			 (?date < "1862-01-01"^^xsd:date) )
	FILTER ( LANG(?eventName)="en" )
}

# The above query selects all major events that happened in 1861. In this case,
# in order for the query to work, it is necessary to specify that "1861-01-01" 
# and "1862-01-01" should be treated as dates and not as normal text.  
# 
